### ISSUE TITLE
No need to include node_modules/

### ISSUE THREAD

**Issue by tanay1337** [ariestiyansyah/MozWall#1]
Great work! You should add `node_modules/` to `.gitignore` as `npm install` will automatically download the required node dependencies.

**Comment by ariestiyansyah** [comment]
Haha, sorry I forgot to add some content to restrict on .gitignore ..

Thanks tanay

**Comment by tanay1337** [comment]
Welcome :)

**Comment by ariestiyansyah** [comment]
Are you from India? You can help me by collecting the image of reps/mozillians from India so in the future I can specific the background by country.

Let me know if you are interest or have question.
